// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWMzYw-64dLR_cYHe3PWmyumtC1X3Qwrw',
    appId: '1:981593503620:web:7d2678ed09fca9ed284fd1',
    messagingSenderId: '981593503620',
    projectId: 'flutterapplication1-3e02d',
    authDomain: 'flutterapplication1-3e02d.firebaseapp.com',
    databaseURL: 'https://flutterapplication1-3e02d-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapplication1-3e02d.firebasestorage.app',
    measurementId: 'G-DL5BTJ1DRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeFAZOa5PYPkUQdCn0VipJOfYpV1BBieE',
    appId: '1:981593503620:android:2686f0526bdb1312284fd1',
    messagingSenderId: '981593503620',
    projectId: 'flutterapplication1-3e02d',
    databaseURL: 'https://flutterapplication1-3e02d-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapplication1-3e02d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdXPn6j22eA3rZTySTxLsh3SkaYsZZiSM',
    appId: '1:981593503620:ios:3b11d36d1fa16f9b284fd1',
    messagingSenderId: '981593503620',
    projectId: 'flutterapplication1-3e02d',
    databaseURL: 'https://flutterapplication1-3e02d-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapplication1-3e02d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdXPn6j22eA3rZTySTxLsh3SkaYsZZiSM',
    appId: '1:981593503620:ios:3b11d36d1fa16f9b284fd1',
    messagingSenderId: '981593503620',
    projectId: 'flutterapplication1-3e02d',
    databaseURL: 'https://flutterapplication1-3e02d-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapplication1-3e02d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWMzYw-64dLR_cYHe3PWmyumtC1X3Qwrw',
    appId: '1:981593503620:web:fb4502c6590c39a9284fd1',
    messagingSenderId: '981593503620',
    projectId: 'flutterapplication1-3e02d',
    authDomain: 'flutterapplication1-3e02d.firebaseapp.com',
    databaseURL: 'https://flutterapplication1-3e02d-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapplication1-3e02d.firebasestorage.app',
    measurementId: 'G-68KW6TK3F8',
  );

}